### ISSUE TITLE
Wrong interpretation of boolean for yml Ansible

### ISSUE THREAD

**Issue by n-meunier** [cpp-playground/nvim_config#1] opened 2022-10-03 05:12 UTC
`nvim` correctly understands and interprets that `yes` is not a boolean value for `yml` files. But in the case of Ansible, this is correct.
This leads to false positive error message:

![Screenshot from 2022-10-03 14-08-24](https://user-images.githubusercontent.com/37764483/193505567-f6c03365-5c3a-49b6-96e6-5d337669f2a4.png)

**Comment by Yuki-cpp** [comment] 2022-10-03 13:49
Should (hopefully) be fixed with [v0.0.1](https://github.com/cpp-playground/nvim_config/releases/tag/v0.0.1).
Let me know if the problem persists

**Comment by Yuki-cpp** [comment] 2022-10-11 07:28
This turned out to be an expected behavior as the ansible provided schema doesn't handle yes/no because of Yaml 2 constraints.
This issue is also now in the user config domain.

**Closed as completed by Yuki-cpp** 2022-10-11 07:28 UTC
Labels: bug, wontfix
